### ISSUE TITLE
Suggestion - Add support for IInitializeWithWindow and IWindowNative

### ISSUE THREAD

**Issue by litewrap** [thebrowsercompany/swift-winrt#167]
Hello swift-winrt team, 

I don't know if this is the right place to ask for this suggestion. 
If not let me know where I can ask. 
Also I posted my issue here: https://forums.swift.org/t/swift-winui-uwp-issue-with-fileopenpicker/72070

I have issue working with FileOpenPicker, FileSavePicker and other classes where we need to call in IInitializeWithWindow to initialize the picker instance with the window handle. Without such initialize, the picker dialog is not displayed and the "invalid handle" is returned.

My understanding is that both IInitializeWithWindow and IWindowNative are not available in the swift-winrt projections and we need to build the support by hand.

From ShObjIdl_core.idl, there is the following IInitializeWithWindow definition:

```
// Implemented by objects the need to be provided a window, often an owner window for displaying UI.
// Used by clients of those objects to provide the window.
[
    uuid(3E68D4BD-7135-4D10-8018-9FB6D9F33FA1),
    object,
    pointer_default(unique)
]
interface IInitializeWithWindow : IUnknown
{
    HRESULT Initialize([in] HWND hwnd);
}
```

Also I found the following infos about IWindowNative
[https://learn.microsoft.com/es/answers/questions/1167924/fixed-fontsize-for-textblock-inside-viewbox](https://learn.microsoft.com/en-us/answers/questions/1167924/fixed-fontsize-for-textblock-inside-viewbox)

```
        [ComImport]
        [InterfaceType(ComInterfaceType.InterfaceIsIUnknown)]
        [Guid("EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB")]
        internal interface IWindowNative
        {
            IntPtr WindowHandle { get; }
        }

```

If think we can translate this to the following idl:

```
[
    uuid(EECDBF0E-BAE9-4CB6-A68E-9598E1CB57BB),
    object,
    pointer_default(unique)
]
interface IWindowNative : IUnknown
{
     IntPtr WindowHandle { get; }
}
```

Edit: IWindowNative appear in microsoft.ui.xaml.window.h in the swift-windowsappsdk package, but no trace in the Generated folder. 

So probably The Browser Company team can add the required code in swift-winrt to support the two missing interfaces and/or provide a kind of generator we can call passing the above definitions and obtain the Swift wrappers we can add to our SwiftPM Windows projects.

In the meantime, some receipt and guidelines I can use to try to build by hand these two Swift wrappers ?

Any other suggestions?

Thanks

**Comment by tristanlabelle** [comment]
Hello @litewrap ! `IInitializeWithWindow` is a COM interface and this project doesn't support code generation for COM. You can still achieve it but it's a little more complex. The simplest way would be to define `IInitializeWithWindow` and `IWindowNative` in C code as structs with virtual tables, build this as a module, import it from Swift, then get the IUnknown for your file picker object (should be exposed via the projection) and call QueryInterface with the GUIDs for the interfaces you want. At that point you're dealing with raw COM so you have to be careful about reference counting.

We have no plans to extend this codebase to generate code for COM interop, but it's something we're interested in doing in the future (likely with a different codebase) since we currently need similar workarounds in Arc.

**Comment by litewrap** [comment]
Thanks a lot @tristanlabelle.
I will explore the COM C wrappers idea and looking forward for such COM interop in a different upcoming package.
